In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_excel("../Raw/kaopen_2023.xls", sheet_name="Sheet1")
df

       cn ccode   country_name  year    kaopen   ka_open
0     111   USA  United States  1970  2.280830  1.000000
1     111   USA  United States  1971  2.280830  1.000000
2     111   USA  United States  1972  2.280830  1.000000
3     111   USA  United States  1973  2.280830  1.000000
4     111   USA  United States  1974  2.280830  1.000000
...   ...   ...            ...   ...       ...       ...
9886  968   ROU        Romania  2019  2.280830  1.000000
9887  968   ROU        Romania  2020  2.029058  0.940341
9888  968   ROU        Romania  2021  1.777286  0.880682
9889  968   ROU        Romania  2022  1.525513  0.821023
9890  968   ROU        Romania  2023  1.273741  0.761365

[9891 rows x 6 columns]

In [4]:
df.describe()

                cn         year       kaopen      ka_open
count  9891.000000  9891.000000  8340.000000  8340.000000
mean    546.913457  1996.601153    -0.000418     0.459446
std     261.068282    15.598422     1.529674     0.362465
min     111.000000  1970.000000    -1.939372     0.000000
25%     311.000000  1983.000000    -1.253876     0.162432
50%     576.000000  1997.000000    -0.174766     0.418133
75%     728.000000  2010.000000     1.525513     0.821023
max     968.000000  2023.000000     2.280830     1.000000

In [3]:
# Inspect some countries for 2023
countries = ["SWE", "USA", "SVK"]

df_23 = df[df["year"] == 2023]
df_23 = df_23[df_23["ccode"].isin(countries)]

df_23

       cn ccode     country_name  year    kaopen   ka_open
53    111   USA    United States  2023  2.280830  1.000000
647   144   SWE           Sweden  2023  2.280830  1.000000
9261  936   SVK  Slovak Republic  2023  0.194631  0.505664

In [5]:
# Export renamed version
df_new = df.rename(columns={"ccode": "iso3"})

df_new = df_new[["iso3", "year", "ka_open"]]

df_new.to_csv("../Clean/kaopen.csv", index=False)