In [28]:
import requests
import pandas as pd
import numpy as np

In [29]:
# Download the json from github
url = "https://raw.githubusercontent.com/dr5hn/countries-states-cities-database/refs/heads/master/json/countries.json"
# Use requests
r = requests.get(url)
r.json()

[{'id': 1,
  'name': 'Afghanistan',
  'iso3': 'AFG',
  'iso2': 'AF',
  'numeric_code': '004',
  'phonecode': '93',
  'capital': 'Kabul',
  'currency': 'AFN',
  'currency_name': 'Afghan afghani',
  'currency_symbol': '؋',
  'tld': '.af',
  'native': 'افغانستان',
  'population': 43844000,
  'gdp': None,
  'region': 'Asia',
  'region_id': 3,
  'subregion': 'Southern Asia',
  'subregion_id': 14,
  'nationality': 'Afghan',
  'area_sq_km': 647500,
  'postal_code_format': None,
  'postal_code_regex': None,
  'timezones': [{'zoneName': 'Asia/Kabul',
    'gmtOffset': 16200,
    'gmtOffsetName': 'UTC+04:30',
    'abbreviation': 'AFT',
    'tzName': 'Afghanistan Time'}],
  'translations': {'br': 'Afghanistan',
   'ko': '아프가니스탄',
   'pt-BR': 'Afeganistão',
   'pt': 'Afeganistão',
   'nl': 'Afghanistan',
   'hr': 'Afganistan',
   'fa': 'افغانستان',
   'de': 'Afghanistan',
   'es': 'Afganistán',
   'fr': 'Afghanistan',
   'ja': 'アフガニスタン',
   'it': 'Afghanistan',
   'zh-CN': '阿富汗',
   'tr': 'Afganistan',
   'ru': 'Афганистан',
   'uk': 'Афганістан',
   'pl': 'Afganistan',
   'ar': 'أفغانستان',
   'hi': 'अफ़ग़ानिस्तान'},
  'latitude': '33.00000000',
  'longitude': '65.00000000',
  'emoji': '🇦🇫',
  'emojiU': 'U+1F1E6 U+1F1EB',
  'wikiDataId': 'Q889'},
 {'id': 2,
  'name': 'Aland Islands',
  'iso3': 'ALA',
  'iso2': 'AX',
  'numeric_code': '248',
  'phonecode': '358',
  'capital': 'Mariehamn',
  'currency': 'EUR',
  'currency_name': 'Euro',
  'currency_symbol': '€',
  'tld': '.ax',
  'native': 'Åland',
  'population': 30654,
  'gdp': None,
  'region': 'Europe',
  'region_id': 4,
  'subregion': 'Northern Europe',
  'subregion_id': 18,
  'nationality': 'Aland Island',
  'area_sq_km': 1580,
  'postal_code_format': '#####',
  'postal_code_regex': '^(?:FI)*(\\d{5})$',
  'timezones': [{'zoneName': 'Europe/Mariehamn',
    'gmtOffset': 7200,
    'gmtOffsetName': 'UTC+02:00',
    'abbreviation': 'EET',
    'tzName': 'Eastern European Time'}],
  'translations': {'br': 'Åland',
   'ko': '올란드 제도',
   'pt-BR': 'Ilhas de Aland',
   'pt': 'Ilhas de Aland',
   'nl': 'Ålandeilanden',
   'hr': 'Ålandski otoci',
   'fa': 'جزایر الند',
   'de': 'Åland',
   'es': 'Alandia',
   'fr': 'Åland',
   'ja': 'オーランド諸島',
   'it': 'Isole Aland',
   'zh-CN': '奥兰群岛',
   'tr': 'Åland Adalari',
   'ru': 'Аландские острова',
   'uk': 'Аландські острови',
   'pl': 'Wyspy Alandzkie',
   'hi': 'अलैंड आइलैंड्स',
   'ar': 'جزر آلاند'},
  'latitude': '60.11666700',
  'longitude': '19.90000000',
  'emoji': '🇦🇽',
  'emojiU': 'U+1F1E6 U+1F1FD',
  'wikiDataId': 'Q5689'},
 {'id': 3,
  'name': 'Albania',
  'iso3': 'ALB',
  'iso2': 'AL',
  'numeric_code': '008',
  'phonecode': '355',
  'capital': 'Tirana',
  'currency': 'ALL',
  'currency_name': 'Albanian lek',
  'currency_symbol': 'Lek',
  'tld': '.al',
  'native': 'Shqipëria',
  'population': 2363314,
  'gdp': 28372,
  'region': 'Europe',
  'region_id': 4,
  'subregion': 'Southern Europe',
  'subregion_id': 16,
  'nationality': 'Albanian ',
  'area_sq_km': 28748,
  'postal_code_format': '####',
  'postal_code_regex': '^(\\d{4})$',
  'timezones': [{'zoneName': 'Europe/Tirane',
    'gmtOffset': 3600,
    'gmtOffsetName': 'UTC+01:00',
    'abbreviation': 'CET',
    'tzName': 'Central European Time'}],
  'translations': {'br': 'Albania',
   'ko': '알바니아',
   'pt-BR': 'Albânia',
   'pt': 'Albânia',
   'nl': 'Albanië',
   'hr': 'Albanija',
   'fa': 'آلبانی',
   'de': 'Albanien',
   'es': 'Albania',
   'fr': 'Albanie',
   'ja': 'アルバニア',
   'it': 'Albania',
   'zh-CN': '阿尔巴尼亚',
   'tr': 'Arnavutluk',
   'ru': 'Албания',
   'uk': 'Албанія',
   'pl': 'Albania',
   'hi': 'अल्बानिया',
   'ar': 'ألبانيا'},
  'latitude': '41.00000000',
  'longitude': '20.00000000',
  'emoji': '🇦🇱',
  'emojiU': 'U+1F1E6 U+1F1F1',
  'wikiDataId': 'Q222'},
 {'id': 4,
  'name': 'Algeria',
  'iso3': 'DZA',
  'iso2': 'DZ',
  'numeric_code': '012',
  'phonecode': '213',
  'capital': 'Algiers',
  'currency': 'DZD',
  'currency_name': 'Algerian dinar',
  'currency_symbol': 'دج',
  'tld': '.dz',
  'native': 'الجزائر',
  'population': 47400000,
  'gdp': 268885,
  'region': 'Africa',
  'region_id': 1,
  'subregion': 'Northern Africa',
  'subregion_id': 1,
  'nationality': 'Algerian',
  'area_sq_km': 2381740,
  'postal_code_format': '#####',
  'postal_code_regex': '^(\\d{5})$',
  'timezones': [{'zoneName': 'Africa/Algiers',
    'gmtOffset': 3600,
    'gmtOffsetName': 'UTC+01:00',
    'abbreviation': 'CET',
    'tzName': 'Central European Time'}],
  'translations': {'br': 'Aljeria',
   'ko': '알제리',
   'pt-BR': 'Argélia',
   'pt': 'Argélia',
   'nl': 'Algerije',
   'hr': 'Alžir',
   'fa': 'الجزایر',
   'de': 'Algerien',
   'es': 'Argelia',
   'fr': 'Algérie',
   'ja': 'アルジェリア',
   'it': 'Algeria',
   'zh-CN': '阿尔及利亚',
   'tr': 'Cezayir',
   'ru': 'Алжир',
   'uk': 'Алжир',
   'pl': 'Algieria',
   'hi': 'एलजीरिया',
   'ar': 'الجزائر'},
  'latitude': '28.00000000',
  'longitude': '3.00000000',
  'emoji': '🇩🇿',
  'emojiU': 'U+1F1E9 U+1F1FF',
  'wikiDataId': 'Q262'},
 {'id': 5,
  'name': 'American Samoa',
  'iso3': 'ASM',
  'iso2': 'AS',
  'numeric_code': '016',
  'phonecode': '1',
  'capital': 'Pago Pago',
  'currency': 'USD',
  'currency_name': 'United States dollar',
  'currency_symbol': '$',
  'tld': '.as',
  'native': 'American Samoa',
  'population': 49710,
  'gdp': None,
  'region': 'Oceania',
  'region_id': 5,
  'subregion': 'Polynesia',
  'subregion_id': 22,
  'nationality': 'American Samoan',
  'area_sq_km': 199,
  'postal_code_format': '#####-####',
  'postal_code_regex': '96799',
  'timezones': [{'zoneName': 'Pacific/Pago_Pago',
    'gmtOffset': -39600,
    'gmtOffsetName': 'UTC-11:00',
    'abbreviation': 'SST',
    'tzName': 'Samoa Standard Time'}],
  'translations': {'br': 'Samoa Amerikan',
   'ko': '아메리칸사모아',
   'pt-BR': 'Samoa Americana',
   'pt': 'Samoa Americana',
   'nl': 'Amerikaans Samoa',
   'hr': 'Američka Samoa',
   'fa': 'ساموآی آمریکا',
   'de': 'Amerikanisch-Samoa',
   'es': 'Samoa Americana',
   'fr': 'Samoa américaines',
   'ja': 'アメリカ領サモア',
   'it': 'Samoa Americane',
   'zh-CN': '美属萨摩亚',
   'tr': 'Amerikan Samoasi',
   'ru': 'Американское Самоа',
   'uk': 'Американське Самоа',
   'pl': 'Samoa Amerykańskie',
   'hi': 'अमेरिकी समोआ',
   'ar': 'ساموا الأمريكية'},
  'latitude': '-14.33333333',
  'longitude': '-170.00000000',
  'emoji': '🇦🇸',
  'emojiU': 'U+1F1E6 U+1F1F8',
  'wikiDataId': 'Q16641'},
 {'id': 6,
  'name': 'Andorra',
  'iso3': 'AND',
  'iso2': 'AD',
  'numeric_code': '020',
  'phonecode': '376',
  'capital': 'Andorra la Vella',
  'currency': 'EUR',
  'currency_name': 'Euro',
  'currency_symbol': '€',
  'tld': '.ad',
  'native': 'Andorra',
  'population': 88306,
  'gdp': 4035,
  'region': 'Europe',
  'region_id': 4,
  'subregion': 'Southern Europe',
  'subregion_id': 16,
  'nationality': 'Andorran',
  'area_sq_km': 468,
  'postal_code_format': 'AD###',
  'postal_code_regex': '^(?:AD)*(\\d{3})$',
  'timezones': [{'zoneName': 'Europe/Andorra',
    'gmtOffset': 3600,
    'gmtOffsetName': 'UTC+01:00',
    'abbreviation': 'CET',
    'tzName': 'Central European Time'}],
  'translations': {'br': 'Andorra',
   'ko': '안도라',
   'pt-BR': 'Andorra',
   'pt': 'Andorra',
   'nl': 'Andorra',
   'hr': 'Andora',
   'fa': 'آندورا',
   'de': 'Andorra',
   'es': 'Andorra',
   'fr': 'Andorre',
   'ja': 'アンドラ',
   'it': 'Andorra',
   'zh-CN': '安道尔',
   'tr': 'Andorra',
   'ru': 'Андорра',
   'uk': 'Андорра',
   'pl': 'Andora',
   'hi': 'एंडोरा',
   'ar': 'أندورا'},
  'latitude': '42.50000000',
  'longitude': '1.50000000',
  'emoji': '🇦🇩',
  'emojiU': 'U+1F1E6 U+1F1E9',
  'wikiDataId': 'Q228'},
 {'id': 7,
  'name': 'Angola',
  'iso3': 'AGO',
  'iso2': 'AO',
  'numeric_code': '024',
  'phonecode': '244',
  'capital': 'Luanda',
  'currency': 'AOA',
  'currency_name': 'Angolan kwanza',
  'currency_symbol': 'Kz',
  'tld': '.ao',
  'native': 'Angola',
  'population': 36170961,
  'gdp': 113343,
  'region': 'Africa',
  'region_id': 1,
  'subregion': 'Middle Africa',
  'subregion_id': 2,
  'nationality': 'Angolan',
  'area_sq_km': 1246700,
  'postal_code_format': None,
  'postal_code_regex': None,
  'timezones': [{'zoneName': 'Africa/Luanda',
    'gmtOffset': 3600,
    'gmtOffsetName': 'UTC+01:00',
    'abbreviation': 'WAT',
    'tzName': 'West Africa Time'}],
  'translations': {'br': 'Angola',
   'ko': '앙골라',
   'pt-BR': 'Angola',
   'pt': 'Angola',
   'nl': 'Angola',
   'hr': 'Angola',
   'fa': 'آنگولا',
   'de': 'Angola',
   'es': 'Angola',
   'fr': 'Angola',
   'ja': 'アンゴラ',
   'it': 'Angola',
   'zh-CN': '安哥拉',
   'tr': 'Angola',
   'ru': 'Ангола',
   'uk': 'Ангола',
   'pl': 'Angola',
   'hi': 'अंगोला',
   'ar': 'أنغولا'},
  'latitude': '-12.50000000',
  'longitude': '18.50000000',
  'emoji': '🇦🇴',
  'emojiU': 'U+1F1E6 U+1F1F4',
  'wikiDataId': 'Q916'},
 {'id': 8,
  'name': 'Anguilla',
  'iso3': 'AIA',
  'iso2': 'AI',
  'numeric_code': '660',
  'phonecode': '1',
  'capital': 'The Valley',
  'currency': 'XCD',
  'currency_name': 'Eastern Caribbean dollar',
  'currency_symbol': '$',
  'tld': '.ai',
  'native': 'Anguilla',
  'population': 16010,
  'gdp': None,
  'region': 'Americas',
  'region_id': 2,
  'subregion': 'Caribbean',
  'subregion_id': 7,
  'nationality': 'Anguillan',
  'area_sq_km': 102,
  'postal_code_format': 'AI-####',
  'postal_code_regex': '^(?:AZ)*(\\d{4})$',
  'timezones': [{'zoneName': 'America/Anguilla',
    'gmtOffset': -14400,
    'gmtOffsetName': 'UTC-04:00',
    'abbreviation': 'AST',
    'tzName': 'Atlantic Standard Time'}],
  'translations': {'br': 'Anguilla',
   'ko': '앵귈라',
   'pt-BR': 'Anguila',
   'pt': 'Anguila',
   'nl': 'Anguilla',
   'hr': 'Angvila',
   'fa': 'آنگویلا',
   'de': 'Anguilla',
   'es': 'Anguilla',
   'fr': 'Anguilla',
   'ja': 'アンギラ',
   'it': 'Anguilla',
   'zh-CN': '安圭拉',
   'tr': 'Anguilla',
   'ru': 'Ангилья',
   'uk': 'Ангілья',
   'pl': 'Anguilla',
   'hi': 'एंगुइला',
   'ar': 'أنغيلا'},
  'latitude': '18.25000000',
  'longitude': '-63.16666666',
  'emoji': '🇦🇮',
  'emojiU': 'U+1F1E6 U+1F1EE',
  'wikiDataId': 'Q25228'},
 {'id': 9,
  'name': 'Antarctica',
  'iso3': 'ATA',
  'iso2': 'AQ',
  'numeric_code': '010',
  'phonecode': '672',
  'capital': '',
  'currency': 'AAD',
  'currency_name': 'Antarctican dollar',
  'currency_symbol': '$',
  'tld': '.aq',
  'native': 'Antarctica',
  'population': None,
  'gdp': None,
  'region': 'Polar',
  'region_id': 6,
  'subregion': '',
  'subregion_id': None,
  'nationality': 'Antarctic',
  'area_sq_km': 14000000,
  'postal_code_format': None,
  'postal_code_regex': None,
  'timezones': [{'zoneName': 'Antarctica/Casey',
    'gmtOffset': 39600,
    'gmtOffsetName': 'UTC+11:00',
    'abbreviation': 'AWST',
    'tzName': 'Australian Western Standard Time'},
   {'zoneName': 'Antarctica/Davis',
    'gmtOffset': 25200,
    'gmtOffsetName': 'UTC+07:00',
    'abbreviation': 'DAVT',
    'tzName': 'Davis Time'},
   {'zoneName': 'Antarctica/DumontDUrville',
    'gmtOffset': 36000,
    'gmtOffsetName': 'UTC+10:00',
    'abbreviation': 'DDUT',
    'tzName': "Dumont d'Urville Time"},
   {'zoneName': 'Antarctica/Mawson',
    'gmtOffset': 18000,
    'gmtOffsetName': 'UTC+05:00',
    'abbreviation': 'MAWT',
    'tzName': 'Mawson Station Time'},
   {'zoneName': 'Antarctica/McMurdo',
    'gmtOffset': 46800,
    'gmtOffsetName': 'UTC+13:00',
    'abbreviation': 'NZDT',
    'tzName': 'New Zealand Daylight Time'},
   {'zoneName': 'Antarctica/Palmer',
    'gmtOffset': -10800,
    'gmtOffsetName': 'UTC-03:00',
    'abbreviation': 'CLST',
    'tzName': 'Chile Summer Time'},
   {'zoneName': 'Antarctica/Rothera',
    'gmtOffset': -10800,
    'gmtOffsetName': 'UTC-03:00',
    'abbreviation': 'ROTT',
    'tzName': 'Rothera Research Station Time'},
   {'zoneName': 'Antarctica/Syowa',
    'gmtOffset': 10800,
    'gmtOffsetName': 'UTC+03:00',
    'abbreviation': 'SYOT',
    'tzName': 'Showa Station Time'},
   {'zoneName': 'Antarctica/Troll',
    'gmtOffset': 0,
    'gmtOffsetName': 'UTC±00',
    'abbreviation': 'GMT',
    'tzName': 'Greenwich Mean Time'},
   {'zoneName': 'Antarctica/Vostok',
    'gmtOffset': 21600,
    'gmtOffsetName': 'UTC+06:00',
    'abbreviation': 'VOST',
    'tzName': 'Vostok Station Time'}],
  'translations': {'br': 'Antarktika',
   'ko': '남극',
   'pt-BR': 'Antártida',
   'pt': 'Antárctida',
   'nl': 'Antarctica',
   'hr': 'Antarktika',
   'fa': 'جنوبگان',
   'de': 'Antarktika',
   'es': 'Antártida',
   'fr': 'Antarctique',
   'ja': '南極大陸',
   'it': 'Antartide',
   'zh-CN': '南极洲',
   'tr': 'Antartika',
   'ru': 'Антарктида',
   'uk': 'Антарктида',
   'pl': 'Antarktyda',
   'hi': 'अंटार्कटिका',
   'ar': 'أنتاركتيكا'},
  'latitude': '-74.65000000',
  'longitude': '4.48000000',
  'emoji': '🇦🇶',
  'emojiU': 'U+1F1E6 U+1F1F6',
  'wikiDataId': 'Q51'},
 {'id': 10,
  'name': 'Antigua and Barbuda',
  'iso3': 'ATG',
  'iso2': 'AG',
  'numeric_code': '028',
  'phonecode': '1',
  'capital': "St. John's",
  'currency': 'XCD',
  'currency_name': 'Eastern Caribbean dollar',
  'currency_symbol': '$',
  'tld': '.ag',
  'native': 'Antigua and Barbuda',
  'population': 103603,
  'gdp': 2373,
  'region': 'Americas',
  'region_id': 2,
  'subregion': 'Caribbean',
  'subregion_id': 7,
  'nationality': 'Antiguan or Barbudan',
  'area_sq_km': 443,
  'postal_code_format': None,
  'postal_code_regex': None,
  'timezones': [{'zoneName': 'America/Antigua',
    'gmtOffset': -14400,
    'gmtOffsetName': 'UTC-04:00',
    'abbreviation': 'AST',
    'tzName': 'Atlantic Standard Time'}],
  'translations': {'br': 'Antigua-ha-Barbuda',
   'ko': '앤티가 바부다',
   'pt-BR': 'Antígua e Barbuda',
   'pt': 'Antígua e Barbuda',
   'nl': 'Antigua en Barbuda',
   'hr': 'Antigva i Barbuda',
   'fa': 'آنتیگوا و باربودا',
   'de': 'Antigua und Barbuda',
   'es': 'Antigua y Barbuda',
   'fr': 'Antigua-et-Barbuda',
   'ja': 'アンティグア・バーブーダ',
   'it': 'Antigua e Barbuda',
   'zh-CN': '安提瓜和巴布达',
   'tr': 'Antigua Ve Barbuda',
   'ru': 'Антигуа и Барбуда',
   'uk': 'Антигуа і Барбуда',
   'pl': 'Antigua i Barbuda',
   'hi': 'अण्टीगुआ और बारबूडा',
   'ar': 'أنتيغوا وبربودا'},
  'latitude': '17.05000000',
  'longitude': '-61.80000000',
  'emoji': '🇦🇬',
  'emojiU': 'U+1F1E6 U+1F1EC',
  'wikiDataId': 'Q781'},
 {'id': 11,
  'name': 'Argentina',
  'iso3': 'ARG',
  'iso2': 'AR',
  'numeric_code': '032',
  'phonecode': '54',
  'capital': 'Buenos Aires',
  'currency': 'ARS',
  'currency_name': 'Argentine peso',
  'currency_symbol': '$',
  'tld': '.ar',
  'native': 'Argentina',
  'population': 46735004,
  'gdp': 683533,
  'region': 'Americas',
  'region_id': 2,
  'subregion': 'South America',
  'subregion_id': 8,
  'nationality': 'Argentine',
  'area_sq_km': 2766890,
  'postal_code_format': '@####@@@',
  'postal_code_regex': '^[A-Z]?\\d{4}[A-Z]{0,3}$',
  'timezones': [{'zoneName': 'America/Argentina/Buenos_Aires',
    'gmtOffset': -10800,
    'gmtOffsetName': 'UTC-03:00',
    'abbreviation': 'ART',
    'tzName': 'Argentina Time'},
   {'zoneName': 'America/Argentina/Catamarca',
    'gmtOffset': -10800,
    'gmtOffsetName': 'UTC-03:00',
    'abbreviation': 'ART',
    'tzName': 'Argentina Time'},
   {'zoneName': 'America/Argentina/Cordoba',
    'gmtOffset': -10800,
    'gmtOffsetName': 'UTC-03:00',
    'abbreviation': 'ART',
    'tzName': 'Argentina Time'},
   {'zoneName': 'America/Argentina/Jujuy',
    'gmtOffset': -10800,
    'gmtOffsetName': 'UTC-03:00',
    'abbreviation': 'ART',
    'tzName': 'Argentina Time'},
   {'zoneName': 'America/Argentina/La_Rioja',
    'gmtOffset': -10800,
    'gmtOffsetName': 'UTC-03:00',
    'abbreviation': 'ART',
    'tzName': 'Argentina Time'},
   {'zoneName': 'America/Argentina/Mendoza',
    'gmtOffset': -10800,
    'gmtOffsetName': 'UTC-03:00',
    'abbreviation': 'ART',
    'tzName': 'Argentina Time'},
   {'zoneName': 'America/Argentina/Rio_Gallegos',
    'gmtOffset': -10800,
    'gmtOffsetName': 'UTC-03:00',
    'abbreviation': 'ART',
    'tzName': 'Argentina Time'},
   {'zoneName': 'America/Argentina/Salta',
    'gmtOffset': -10800,
    'gmtOffsetName': 'UTC-03:00',
    'abbreviation': 'ART',
    'tzName': 'Argentina Time'},
   {'zoneName': 'America/Argentina/San_Juan',
    'gmtOffset': -10800,
    'gmtOffsetName': 'UTC-03:00',
    'abbreviation': 'ART',
    'tzName': 'Argentina Time'},
   {'zoneName': 'America/Argentina/San_Luis',
    'gmtOffset': -10800,
    'gmtOffsetName': 'UTC-03:00',
    'abbreviation': 'ART',
    'tzName': 'Argentina Time'},
   {'zoneName': 'America/Argentina/Tucuman',
    'gmtOffset': -10800,
    'gmtOffsetName': 'UTC-03:00',
    'abbreviation': 'ART',
    'tzName': 'Argentina Time'},
   {'zoneName': 'America/Argentina/Ushuaia',
    'gmtOffset': -10800,
    'gmtOffsetName': 'UTC-03:00',
    'abbreviation': 'ART',
    'tzName': 'Argentina Time'}],
  'translations': {'br': "Arc'hantina",
   'ko': '아르헨티나',
   'pt-BR': 'Argentina',
   'pt': 'Argentina',
   'nl': 'Argentinië',
   'hr': 'Argentina',
   'fa': 'آرژانتین',
   'de': 'Argentinien',
   'es': 'Argentina',
   'fr': 'Argentine',
   'ja': 'アルゼンチン',
   'it': 'Argentina',
   'zh-CN': '阿根廷',
   'tr': 'Arjantin',
   'ru': 'Аргентина',
   'uk': 'Аргентина',
   'pl': 'Argentyna',
   'hi': 'अर्जेंटीना',
   'ar': 'الأرجنتين'},
  'latitude': '-34.00000000',
  'longitude': '-64.00000000',
  'emoji': '🇦🇷',
  'emojiU': 'U+1F1E6 U+1F1F7',
  'wikiDataId': 'Q414'},
 {'id': 12,
  'name': 'Armenia',
  'iso3': 'ARM',
  'iso2': 'AM',
  'numeric_code': '051',
  'phonecode': '374',
  'capital': 'Yerevan',
  'currency': 'AMD',
  'currency_name': 'Armenian dram',
  'currency_symbol': '֏',
  'tld': '.am',
  'native': 'Հայաստան',
  'population': 3081100,
  'gdp': 26258,
  'region': 'Asia',
  'region_id': 3,
  'subregion': 'Western Asia',
  'subregion_id': 11,
  'nationality': 'Armenian',
  'area_sq_km': 29800,
  'postal_code_format': '######',
  'postal_code_regex': '^(\\d{6})$',
  'timezones': [{'zoneName': 'Asia/Yerevan',
    'gmtOffset': 14400,
    'gmtOffsetName': 'UTC+04:00',
    'abbreviation': 'AMT',
    'tzName': 'Armenia Time'}],
  'translations': {'br': 'Armenia',
   'ko': '아르메니아',
   'pt-BR': 'Armênia',
   'pt': 'Arménia',
   'nl': 'Armenië',
   'hr': 'Armenija',
   'fa': 'ارمنستان',
   'de': 'Armenien',
   'es': 'Armenia',
   'fr': 'Arménie',
   'ja': 'アルメニア',
   'it': 'Armenia',
   'zh-CN': '亚美尼亚',
   'tr': 'Ermenistan',
   'ru': 'Армения',
   'uk': 'Вірменія',
   'pl': 'Armenia',
   'hi': 'आर्मीनिया',
   'ar': 'أرمينيا'},
  'latitude': '40.00000000',
  'longitude': '45.00000000',
  'emoji': '🇦🇲',
  'emojiU': 'U+1F1E6 U+1F1F2',
  'wikiDataId': 'Q399'},
 {'id': 13,
  'name': 'Aruba',
  'iso3': 'ABW',
  'iso2': 'AW',
  'numeric_code': '533',
  'phonecode': '297',
  'capital': 'Oranjestad',
  'currency': 'AWG',
  'currency_name': 'Aruban florin',
  'currency_symbol': 'ƒ',
  'tld': '.aw',
  'native': 'Aruba',
  'population': 107566,
  'gdp': 4100,
  'region': 'Americas',
  'region_id': 2,
  'subregion': 'Caribbean',
  'subregion_id': 7,
  'nationality': 'Aruban',
  'area_sq_km': 193,
  'postal_code_format': None,
  'postal_code_regex': None,
  'timezones': [{'zoneName': 'America/Aruba',
    'gmtOffset': -14400,
    'gmtOffsetName': 'UTC-04:00',
    'abbreviation': 'AST',
    'tzName': 'Atlantic Standard Time'}],
  'translations': {'br': 'Aruba',
   'ko': '아루바',
   'pt-BR': 'Aruba',
   'pt': 'Aruba',
   'nl': 'Aruba',
   'hr': 'Aruba',
   'fa': 'آروبا',
   'de': 'Aruba',
   'es': 'Aruba',
   'fr': 'Aruba',
   'ja': 'アルバ',
   'it': 'Aruba',
   'zh-CN': '阿鲁巴',
   'tr': 'Aruba',
   'ru': 'Аруба',
   'uk': 'Аруба',
   'pl': 'Aruba',
   'hi': 'अरूबा',
   'ar': 'أروبا'},
  'latitude': '12.50000000',
  'longitude': '-69.96666666',
  'emoji': '🇦🇼',
  'emojiU': 'U+1F1E6 U+1F1FC',
  'wikiDataId': 'Q21203'},
 {'id': 14,
  'name': 'Australia',
  'iso3': 'AUS',
  'iso2': 'AU',
  'numeric_code': '036',
  'phonecode': '61',
  'capital': 'Canberra',
  'currency': 'AUD',
  'currency_name': 'Australian dollar',
  'currency_symbol': '$',
  'tld': '.au',
  'native': 'Australia',
  'population': 27400013,
  'gdp': 1771681,
  'region': 'Oceania',
  'region_id': 5,

In [30]:
# Extract the iso3 code, country name, latitude, and longitude
countries = [{"iso3": x.get("iso3"), "currency": x.get("currency")
                , "name": x.get("name"), "latitude": x.get("latitude")
                , "longitude": x.get("longitude")} 
             for x in r.json()]

countries_df = pd.DataFrame(countries)

countries_df["latitude"] = pd.to_numeric(countries_df["latitude"], errors="coerce")
countries_df["longitude"] = pd.to_numeric(countries_df["longitude"], errors="coerce")

countries_df

    iso3 currency                       name   latitude  longitude
0    AFG      AFN                Afghanistan  33.000000       65.0
1    ALA      EUR              Aland Islands  60.116667       19.9
2    ALB      ALL                    Albania  41.000000       20.0
3    DZA      DZD                    Algeria  28.000000        3.0
4    ASM      USD             American Samoa -14.333333     -170.0
..   ...      ...                        ...        ...        ...
245  WLF      XPF  Wallis and Futuna Islands -13.300000     -176.2
246  ESH      MAD             Western Sahara  24.500000      -13.0
247  YEM      YER                      Yemen  15.000000       48.0
248  ZMB      ZMW                     Zambia -15.000000       30.0
249  ZWE      ZWL                   Zimbabwe -20.000000       30.0

[250 rows x 5 columns]

In [31]:
countries_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   iso3       250 non-null    str
 1   currency   250 non-null    str
 2   name       250 non-null    str
 3   latitude   250 non-null    float64
 4   longitude  250 non-null    float64
dtypes: float64(2), str(3)
memory usage: 9.9 KB

In [32]:
# Calculate distance between countries using the Haversine formula
from math import radians, sin, cos, sqrt, atan2

def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # Earth radius in km
    dlat = radians(lat2 - lat1)
    dlon = radians(lon2 - lon1)
    a = sin(dlat/2)**2 + cos(radians(lat1)) * cos(radians(lat2)) * sin(dlon/2)**2
    return R * 2 * atan2(sqrt(a), sqrt(1-a))

In [35]:
# Get all pairs possible
from itertools import product
from tqdm import tqdm

pairs = list(product(countries_df["iso3"].unique(), repeat=2))

distances = []
for iso3_1, iso3_2 in tqdm(pairs):
    lat1 = countries_df[countries_df["iso3"] == iso3_1]["latitude"].values[0]
    lon1 = countries_df[countries_df["iso3"] == iso3_1]["longitude"].values[0]
    lat2 = countries_df[countries_df["iso3"] == iso3_2]["latitude"].values[0]
    lon2 = countries_df[countries_df["iso3"] == iso3_2]["longitude"].values[0]
    try:
        distance = haversine(lat1, lon1, lat2, lon2)
    except Exception as e:
        distance = np.nan
        print(f"Error calculating distance between {iso3_1} and {iso3_2}: {e}")
    distances.append({"iso3_i": iso3_1, "iso3_j": iso3_2, "distance_km": distance})

distances_df = pd.DataFrame(distances)
distances_df

 33%|███▎      | 20539/62500 [00:44<02:22, 294.69it/s]

Error calculating distance between GHA and TUV: math domain error

 92%|█████████▏| 57759/62500 [02:04<00:09, 495.65it/s]

Error calculating distance between TUV and GHA: math domain error

100%|██████████| 62500/62500 [02:15<00:00, 459.60it/s]

      iso3_i iso3_j   distance_km
0        AFG    AFG      0.000000
1        AFG    ALA   4436.559161
2        AFG    ALB   4047.637966
3        AFG    DZA   5881.179067
4        AFG    ASM  14114.459916
...      ...    ...           ...
62495    ZWE    WLF  15332.596720
62496    ZWE    ESH   6792.169129
62497    ZWE    YEM   4361.029497
62498    ZWE    ZMB    555.974633
62499    ZWE    ZWE      0.000000

[62500 rows x 3 columns]

In [36]:
# Save to clean csv
file_path = "../Clean/countries_distances.csv"
distances_df.to_csv(file_path, index=False)