In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../Raw/dataset_2026-05-06T12_34_25.201892644Z_DEFAULT_INTEGRATION_IMF.MCM_FDI_1.0.0.csv")
df

,DATASET,SERIES_CODE,OBS_MEASURE,COUNTRY,INDICATOR,FREQUENCY,SCALE,DECIMALS_DISPLAYED,UNIT,OVERLAP,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,IMF.MCM:FDI(1.0.0),SWE.FDD_IX.A,OBS_VALUE,Sweden,Financial Institutions Depth Index,Annual,Units,Three,NaN,NaN,...,0.995,0.978,0.991,0.978,0.989,0.969,0.978,0.989,1.000,1.000
1,IMF.MCM:FDI(1.0.0),CAN.FDA_IX.A,OBS_VALUE,Canada,Financial Institutions Access Index,Annual,Units,Three,NaN,NaN,...,0.773,0.774,0.763,0.761,0.758,0.751,0.734,0.727,0.722,0.727
2,IMF.MCM:FDI(1.0.0),MDV.FDA_IX.A,OBS_VALUE,Maldives,Financial Institutions Access Index,Annual,Units,Three,NaN,NaN,...,0.202,0.210,0.207,0.218,0.216,0.248,0.280,0.289,0.312,0.324
3,IMF.MCM:FDI(1.0.0),MDV.FMD_IX.A,OBS_VALUE,Maldives,Financial Markets Depth Index,Annual,Units,Three,NaN,NaN,...,0.009,0.006,0.006,0.006,0.006,0.007,0.007,0.009,0.008,0.012
4,IMF.MCM:FDI(1.0.0),COG.FDD_IX.A,OBS_VALUE,"Congo, Republic of",Financial Institutions Depth Index,Annual,Units,Three,NaN,NaN,...,0.032,0.036,0.044,0.049,0.077,0.074,0.062,0.053,0.051,0.051
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1723,IMF.MCM:FDI(1.0.0),MKD.FDA_IX.A,OBS_VALUE,"North Macedonia, Republic of",Financial Institutions Access Index,Annual,Units,Three,NaN,NaN,...,0.500,0.498,0.519,0.527,0.548,0.548,0.553,0.538,0.545,0.515
1724,IMF.MCM:FDI(1.0.0),SWZ.FMD_IX.A,OBS_VALUE,"Eswatini, Kingdom of",Financial Markets Depth Index,Annual,Units,Three,NaN,NaN,...,0.017,0.017,0.017,0.017,0.017,0.017,0.017,0.017,0.017,0.017
1725,IMF.MCM:FDI(1.0.0),GXALL_COUNTRIES.FDE_IX.A,OBS_VALUE,All Countries,Financial Institutions Efficiency Index,Annual,Units,Three,NaN,NaN,...,0.552,0.553,0.555,0.556,0.556,0.566,0.566,0.580,0.576,0.576
1726,IMF.MCM:FDI(1.0.0),MKD.FDD_IX.A,OBS_VALUE,"North Macedonia, Republic of",Financial Institutions Depth Index,Annual,Units,Three,NaN,NaN,...,0.155,0.165,0.166,0.175,0.184,0.182,0.189,0.194,0.202,0.220
1727,IMF.MCM:FDI(1.0.0),GXALL_COUNTRIES.FI_IX.A,OBS_VALUE,All Countries,Financial Institutions Index,Annual,Units,Three,NaN,NaN,...,0.401,0.407,0.412,0.415,0.417,0.420,0.420,0.423,0.423,0.426

In [4]:
df["INDICATOR"].value_counts()

INDICATOR
Financial Institutions Depth Index         192
Financial Institutions Access Index        192
Financial Markets Depth Index              192
Financial Markets Efficiency Index         192
Financial Markets Access Index             192
Financial Markets Index                    192
Financial Development Index                192
Financial Institutions Efficiency Index    192
Financial Institutions Index               192
Name: count, dtype: int64

In [5]:
# We want to use the Financial Development Index, since it is the aggregate.
df = df[df["INDICATOR"]=="Financial Development Index"]

In [6]:
yr_cols = [c for c in df.columns if c.startswith("20") and len(c)==4]
yr_cols

['2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020']

In [7]:
# Melt into long format
# Keep COUNTRY and INDICATOR as id_vars, and melt the year columns into 'year' and 'value'
df_long = df.melt(id_vars=["COUNTRY", "INDICATOR"], value_vars=yr_cols, var_name="year", value_name="value")
df_long["year"] = df_long["year"].astype(int)
df_long

,COUNTRY,INDICATOR,year,value
0,Chile,Financial Development Index,2000,0.386
1,Hungary,Financial Development Index,2000,0.400
2,Morocco,Financial Development Index,2000,0.264
3,"Ethiopia, The Federal Democratic Republic of",Financial Development Index,2000,0.101
4,Switzerland,Financial Development Index,2000,0.986
...,...,...,...,...
4027,"Eswatini, Kingdom of",Financial Development Index,2020,0.155
4028,Low-Income and Developing Countries,Financial Development Index,2020,0.142
4029,"North Macedonia, Republic of",Financial Development Index,2020,0.252
4030,Middle East and Central Asia,Financial Development Index,2020,0.266
4031,Europe,Financial Development Index,2020,0.503

In [8]:
# Import pycountry and map them
import pycountry

name_to_iso3 = {country.name: country.alpha_3 for country in pycountry.countries}

df_long["iso3"] = df_long["COUNTRY"].map(name_to_iso3)

In [9]:
# Expand with this one
EUROSTAT_COUNTRY_TO_ISO3 = {
    "Austria": "AUT",
    "Belgium": "BEL",
    "Bulgaria": "BGR",
    "Croatia": "HRV",
    "Cyprus": "CYP",
    "Czechia": "CZE",
    "Czech Republic": "CZE",
    "Denmark": "DNK",
    "Estonia": "EST",
    "Estonia, Republic of": "EST",
    "Finland": "FIN",
    "France": "FRA",
    "Germany": "DEU",
    "Greece": "GRC",
    "Hungary": "HUN",
    "Ireland": "IRL",
    "Italy": "ITA",
    "Latvia": "LVA",
    "Latvia, Republic of": "LVA",
    "Lithuania": "LTU",
    "Lithuania, Republic of": "LTU",
    "Luxembourg": "LUX",
    "Malta": "MLT",
    "Netherlands": "NLD",
    "Netherlands, The": "NLD",
    "Poland": "POL",
    "Poland, Republic of": "POL",
    "Portugal": "PRT",
    "Romania": "ROU",
    "Slovakia": "SVK",
    "Slovak Republic": "SVK",
    "Slovenia": "SVN",
    "Slovenia, Republic of": "SVN",
    "Spain": "ESP",
    "Sweden": "SWE",
    "United Kingdom": "GBR",
    "Norway": "NOR",
    "Switzerland": "CHE",
    "United States": "USA"
}

for country, iso3 in EUROSTAT_COUNTRY_TO_ISO3.items():
    df_long.loc[df_long["COUNTRY"] == country, "iso3"] = iso3

In [10]:
# Get which ones dont map and print them
print("\n".join(df_long[df_long["iso3"].isna()]["COUNTRY"].unique()))

Ethiopia, The Federal Democratic Republic of
Congo, Republic of
Bahamas, The
Venezuela, República Bolivariana de
Azerbaijan, Republic of
Lesotho, Kingdom of
Armenia, Republic of
Madagascar, Republic of
Serbia, Republic of
South Sudan, Republic of
Türkiye, Republic of
St. Vincent and the Grenadines
Yemen, Republic of
St. Lucia
Vietnam
Bahrain, Kingdom of
Egypt, Arab Republic of
St. Kitts and Nevis
Macao Special Administrative Region, People's Republic of China
Marshall Islands, Republic of the
Eritrea, The State of
Mauritania, Islamic Republic of
São Tomé and Príncipe, Democratic Republic of
Equatorial Guinea, Republic of
Aruba, Kingdom of the Netherlands
Congo, Democratic Republic of the
Gambia, The
Belarus, Republic of
Fiji, Republic of
Croatia, Republic of
Mozambique, Republic of
Kazakhstan, Republic of
Kyrgyz Republic
Tajikistan, Republic of
Bolivia
Uzbekistan, Republic of
Comoros, Union of the
China, People's Republic of
Timor-Leste, Democratic Republic of
Emerging Markets
Africa
Hong Kong Special Administrative Region, People's Republic of China
Latin America and the Caribbean (LAC)
All Countries
Advanced Markets
Asia and Pacific
Eswatini, Kingdom of
Low-Income and Developing Countries
North Macedonia, Republic of
Middle East and Central Asia
Europe

In [11]:
# Rename value to financial_development_index
df_long = df_long.rename(columns={"value": "financial_development_index"})
df_long = df_long[["iso3", "year", "financial_development_index"]]
df_long

     iso3  year  financial_development_index
0     CHL  2000                        0.386
1     HUN  2000                        0.400
2     MAR  2000                        0.264
3     NaN  2000                        0.101
4     CHE  2000                        0.986
...   ...   ...                          ...
4027  NaN  2020                        0.155
4028  NaN  2020                        0.142
4029  NaN  2020                        0.252
4030  NaN  2020                        0.266
4031  NaN  2020                        0.503

[4032 rows x 3 columns]

In [12]:
df_long.describe()

              year  financial_development_index
count  4032.000000                  4032.000000
mean   2010.000000                     0.302667
std       6.056052                     0.226841
min    2000.000000                     0.000000
25%    2005.000000                     0.118000
50%    2010.000000                     0.232000
75%    2015.000000                     0.427000
max    2020.000000                     1.000000

In [13]:
df_long.to_csv("../Clean/IMF_Financial_Development_Index.csv", index=False)